user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Homepage:homepage}

user_registration:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }

login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout

show_profile:
    path: /profile/show/{username}
    defaults: { _controller: UserBundle:Profile:show}

edit_profile:
    path: /profile/edit
    defaults: { _controller: UserBundle:Profile:edit}

admin_dashboard:
    path: /admin
    defaults: { _controller: UserBundle:Admin:main}

admin_dashboard_user:
    path: /admin/users
    defaults: { _controller: UserBundle:Admin:users}

admin_dashboard_user_add:
    path: /admin/users/add
    defaults: { _controller: UserBundle:Admin:addUser}

admin_dashboard_user_edit:
    path: /admin/users/edit/{id}
    defaults: { _controller: UserBundle:Admin:editUser}

admin_dashboard_user_delete:
    path: /admin/users/delete/{id}
    defaults: { _controller: UserBundle:Admin:deleteUser}

admin_dashboard_offer:
    path: /admin/offers
    defaults: { _controller: UserBundle:Admin:offers}

admin_dashboard_offer_add:
    path: /admin/offers/add
    defaults: { _controller: UserBundle:Admin:addArticle}

admin_dashboard_offer_edit:
    path: /admin/offers/edit/{id}
    defaults: { _controller: UserBundle:Admin:editArticle}

admin_dashboard_offer_delete:
    path: /admin/offers/delete/{id}
    defaults: { _controller: UserBundle:Admin:deleteArticle}

admin_dashboard_review:
    path: /admin/reviews
    defaults: { _controller: UserBundle:Admin:review}

admin_dashboard_review_delete:
    path: /admin/reviews/delete/{id}
    defaults: { _controller: UserBundle:Admin:deleteReview}
