user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Homepage:homepage}

user_registration:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }

login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout

show_profile:
    path: /profile/show/{username}
    defaults: { _controller: UserBundle:Profile:show}

edit_profile:
    path: /profile/edit
    defaults: { _controller: UserBundle:Profile:edit}