EntityBundle\Entity\Glasses:
    type: entity
    table: null
    repositoryClass: EntityBundle\Repository\GlassesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        brand:
            type: string
            length: 100
        sex:
            type: string
            length: 100
        shape:
            type: string
            length: 100
        leftcorrection:
            type: integer
            length: 100
        rightcorrection:
            type: integer
            length: 100
        glassdiameter:
            type: integer
            lenght: 100
        glassbridge:
            type: integer
            lenght: 100
        glassarm:
            type: integer
            lenght: 100
        glasstype:
            type: string
            length: 100
        color:
            type: string
            length: 100
        price:
            type: integer
            length: 100
        firstImageFile :
            - File:
                 maxSize: 6000000
        firstImageName :
            type : string
            length : 255
        secondImageFile :
            - File:
                 maxSize: 6000000
        secondImageName :
            type : string
            length : 255
        thirdImageFile :
            - File:
                 maxSize: 6000000
        thirdImageName :
            type : string
            length : 255

    manyToOne:
        user:
            targetEntity: EntityBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
